export { default as Input} from './Input'
export { default as Save} from './Save'
export { default as Posts} from './Posts'
export { default as Form} from './Form'
export { default as Image} from './Image'
export { default as Gallery} from './Gallery'
